from __future__ import annotations

import os
import socket
import uuid
import re

# Firestore room
MQTT_T_VAL_FORWARD = 1
MQTT_T_VAL_BACKWARD = 2
MQTT_T_VAL_LEFT = 3
MQTT_T_VAL_RIGHT = 4
MQTT_T_VAL_STOP = 0
MQTT_T_VAL_SPEED_UP = 5
MQTT_T_VAL_SLOW_DOWN = 6
MQTT_T_VAL_EMERGENCY_STOP = 7
MQTT_T_VAL_RESET = 8
MQTT_T_VAL_CAMERA_UP = 9
MQTT_T_VAL_CAMERA_DOWN = 10
MQTT_T_VAL_CAMERA_LEFT = 11
MQTT_T_VAL_CAMERA_RIGHT = 12
MQTT_T_VAL_CAMERA_RESET = 13
MQTT_T_VAL_RPI_RESTART = 14
MQTT_T_VAL_RPI_SHUTDOWN = 15
MQTT_T_VAL_SERVO_ROTATE_TEST = 16 #//servo 1
MQTT_T_VAL_SERVO2_ROTATE_TEST = 17  #//servo 2